services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: prompt_postgres
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: prompt
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
